### PR TITLE
Add Node 7.6.0

### PR DESCRIPTION
**Pull request by yamalight**
Hey there! Node 7.6 came out yesterday and I thought I'd do a quick PR to add it to your awesome node-yarn image.
Let me know if that looks good - or needs any changes.

### CODE REVIEW

**Comment by kkarczmarczyk** [comment]
You're faster than me, impressive! Looks good, but annotation in readme.md file is missing.

**Comment by yamalight** [comment]
@kkarczmarczyk ah, fair point. Added, please check :)

**Comment by kkarczmarczyk** [comment]
@yamalight great!

**Comment by yamalight** [comment]
sweet, thanks for quick merge 👍

**Comment by kkarczmarczyk** [comment]
now I'm waiting in queue for automated build for new 7.6 images in hub.docker.com, so please be patient for few minutes ;)

**Comment by yamalight** [comment]
sounds good 👍

**Pull request merged**
